server:
  port: 8080
  shutdown: graceful

movie:
  url: http://localhost:8080

spring:
  application:
    name: ticket-service

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      group:
        readiness:
          include: readinessState, movie
